#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${RDS_ENDPOINT}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${USERNAME}
#    password: ${PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#        debug: true
#
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: false
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#    defer-datasource-initialization: true
#  sql.init.mode: always
#
#  # RabbitMQ 연결 정보
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
## RabbitMQ queue, exchange, routing-key 정보
#rabbitmq:
#  queue:
#    name: sample.queue
#  exchange:
#    name: sample.exchange
#  routing:
#    key: sample.key
